// Initialize a variable to store the recovery code generated by the system
let generatedCode = "";
// Initialize a variable to store the email address targeted for password recovery
let targetEmail = "";

// Attach an event listener that runs when the entire HTML document has finished loading
window.onload = () => {
    // Get the theme toggle switch element by its ID
    const themeToggle = document.getElementById('theme-toggle');
    // Check local storage to see if the user previously selected the dark theme
    if (localStorage.getItem('theme') === 'dark') {
        // If they did, add the 'darkmode' class to the document body to apply dark styles
        document.body.classList.add('darkmode');
        // Check if the theme toggle element actually exists on the current page
        if (themeToggle) {
            // Set the toggle switch to the 'checked' state visually
            themeToggle.checked = true;
        }
    }
    // Check again if the theme toggle exists on the current page to attach a listener
    if (themeToggle) {
        // Attach an event listener that fires whenever the toggle switch is flipped
        themeToggle.addEventListener('change', () => {
            // Toggle the 'darkmode' CSS class on the body on or off
            document.body.classList.toggle('darkmode');
            // Determine if the 'darkmode' class is currently applied to the body
            const currentTheme = document.body.classList.contains('darkmode') ? 'dark' : 'light';
            // Save the newly determined theme preference into local storage for future visits
            localStorage.setItem('theme', currentTheme);
        });
    }

    // --- LOGIN PAGE LOGIC ---
    // Retrieve the PIN input field specifically from the login page
    const pinField = document.getElementById('loginPin');
    // If the PIN field exists, it means we are currently on the index.html page
    if (pinField) {
        // Add an event listener to trigger every time the user types in the PIN field
        pinField.addEventListener('input', function () {
            // Strip out any characters that are not numbers (0-9) to force numeric input
            this.value = this.value.replace(/[^0-9]/g, '');
            // Check if the length of the inputted PIN is exactly 4 digits long
            if (this.value.length === 4) {
                // Fetch the stored user database from local storage, or initialize an empty object if none exists
                const users = JSON.parse(localStorage.getItem('mathTrackUsers')) || {};
                // Initialize a temporary variable to hold the matched account object
                let account = null;
                // Loop through every email key stored inside the users database
                for (let email in users) {
                    // Check if the PIN associated with the current looped user matches the typed PIN
                    if (users[email].pin === this.value) {
                        // If it matches, assign that user's object to the account variable
                        account = users[email];
                        // Break out of the loop since the correct account has been found
                        break;
                    }
                }
                // Check if a matching account was successfully found in the loop
                if (account) {
                    // Save the matched account to local storage as the 'currentUser' to establish an active session
                    localStorage.setItem('currentUser', JSON.stringify(account));
                    // Dim the opacity of the body element to 50% to create a visual fade out effect
                    document.body.style.opacity = '0.5';
                    // Apply a smooth transition effect to the opacity change
                    document.body.style.transition = 'opacity 0.2s ease';
                    // Wait for 250 milliseconds to let the fade animation play out
                    setTimeout(() => { 
                        // Redirect the user's browser to the class selection portal
                        window.location.href = "select.html"; 
                    }, 250);
                } else {
                    // Alert the user via a popup box that the PIN they entered does not exist
                    alert("Incorrect PIN.");
                    // Clear the input field so the user can try entering their PIN again
                    this.value = "";
                }
            }
        });
    }

    // --- SIGNUP PAGE LOGIC ---
    // Retrieve the signup button from the DOM
    const signupBtn = document.getElementById('signupBtn');
    // If the signup button exists, it means we are currently on the signup.html page
    if (signupBtn) {
        // Define an array of all the input field IDs present on the signup form
        const signupInputs = ['pin', 'confPin', 'firstName', 'lastName', 'email', 'appPassword'];
        // Iterate over each ID in the array
        signupInputs.forEach(id => {
            // Retrieve the HTML element corresponding to the current ID
            const el = document.getElementById(id);
            // Check to ensure the element was found in the DOM
            if (el) {
                // Add an input event listener to run the signup validation function on every keystroke
                el.addEventListener('input', validateSignupForm);
            }
        });
        // Call the helper function to attach the show/hide eye logic to the App Password field
        setupEyeToggle('appPassword', 'toggleAppPass');
        // Call the helper function to attach the show/hide eye logic to the main PIN field
        setupEyeToggle('pin', 'togglePin');
        // Call the helper function to attach the show/hide eye logic to the Confirm PIN field
        setupEyeToggle('confPin', 'toggleConfPin');
    }

    // --- RECOVERY PAGE LOGIC ---
    // Retrieve the reset password button from the DOM
    const resetBtn = document.getElementById('resetBtn');
    // If the reset button exists, it means we are currently on the recovery.html page
    if (resetBtn) {
        // Define an array of input field IDs required for step 2 of the recovery process
        const recoveryInputs = ['newPin', 'confPin', 'recoveryCode'];
        // Iterate over each ID in the recovery array
        recoveryInputs.forEach(id => {
            // Retrieve the HTML element corresponding to the current ID
            const el = document.getElementById(id);
            // Check to ensure the element was found in the DOM
            if (el) {
                // Add an input event listener to run the recovery validation function on every keystroke
                el.addEventListener('input', validateRecoveryForm);
            }
        });
        // Call the helper function to attach the show/hide eye logic to the new PIN field
        setupEyeToggle('newPin', 'toggleNewPin');
        // Call the helper function to attach the show/hide eye logic to the Confirm PIN field
        setupEyeToggle('confPin', 'toggleConfPin');
    }
};

// --- GLOBAL FUNCTIONS ---

// Define a globally accessible function to toggle password visibility on the main login screen
window.togglePassword = function() {
    // Get the login PIN input field element
    const pinInput = document.getElementById('loginPin');
    // Find the next sibling element in the DOM, which is the eye icon button
    const eyeIcon = pinInput.nextElementSibling;
    // Check if the input field's type attribute is currently set to 'password' (hidden characters)
    if (pinInput.type === "password") {
        // Change the type attribute to 'text' to reveal the inputted characters
        pinInput.type = "text";
        // Change the button's text content to a lock emoji to indicate it can be hidden again
        eyeIcon.textContent = "🔒";
    } else {
        // Change the type attribute back to 'password' to conceal the characters
        pinInput.type = "password";
        // Change the button's text content back to an eye emoji to indicate it can be revealed again
        eyeIcon.textContent = "👁️";
    }
};

// Define a globally accessible function to simulate quitting the application
window.quitApp = function() {
    // Prompt the user with a confirmation dialog box asking if they want to close the portal
    if (confirm("Close MathTrack Portal?")) {
        // Attempt to close the current browser window (often blocked by modern browsers if not opened via script)
        window.close();
        // Replace the entire body of the HTML with a message instructing the user to manually close the tab
        document.body.innerHTML = "<h1 style='text-align:center; margin-top:50px;'>You may now close this tab.</h1>";
    }
};

// Define a helper function to set up eye toggle functionality for dynamic inputs on signup/recovery
function setupEyeToggle(inputId, toggleId) {
    // Locate the target input field element by its provided ID
    const inputEl = document.getElementById(inputId);
    // Locate the target toggle span/button element by its provided ID
    const toggleEl = document.getElementById(toggleId);
    // Verify that both the input and the toggle element exist on the page
    if (inputEl && toggleEl) {
        // Attach a click event listener directly to the toggle element
        toggleEl.addEventListener('click', function () {
            // Determine the new type: if it is currently 'password', set to 'text', otherwise set back to 'password'
            const type = inputEl.getAttribute('type') === 'password' ? 'text' : 'password';
            // Apply the determined type back to the input element
            inputEl.setAttribute('type', type);
            // Change the text content of the clicked element to the corresponding emoji
            this.textContent = type === 'password' ? '👁️' : '🔒';
        });
    }
}

// Define a globally accessible function to validate the signup form dynamically
window.validateSignupForm = function() {
    // Retrieve the current string value from the primary PIN input field
    const pin = document.getElementById('pin').value;
    // Retrieve the current string value from the confirmation PIN input field
    const conf = document.getElementById('confPin').value;

    // Create a boolean flag evaluating if the primary PIN is exactly 4 characters long
    let isLengthValid = pin.length === 4;
    // Create a boolean flag evaluating if the primary PIN consists solely of digits using RegEx
    let isNumValid = /^\d+$/.test(pin);
    // Create a boolean flag evaluating if the primary PIN matches the confirm PIN and is not blank
    let isMatchValid = (pin === conf) && pin.length > 0;

    // Update the CSS class of the length rule div to 'rule valid' if true, otherwise just 'rule'
    document.getElementById('rule-length').className = isLengthValid ? 'rule valid' : 'rule';
    // Update the text of the length rule div to show a green checkmark or red X respectively
    document.getElementById('rule-length').innerText = isLengthValid ? '✅ Must be exactly 4 characters' : '❌ Must be exactly 4 characters';
    
    // Update the CSS class of the numeric rule div to 'rule valid' if true and not empty, otherwise 'rule'
    document.getElementById('rule-number').className = isNumValid && pin.length > 0 ? 'rule valid' : 'rule';
    // Update the text of the numeric rule div to show a green checkmark or red X respectively
    document.getElementById('rule-number').innerText = isNumValid && pin.length > 0 ? '✅ Must contain only numbers' : '❌ Must contain only numbers';
    
    // Update the CSS class of the match rule div to 'rule valid' if true, otherwise 'rule'
    document.getElementById('rule-match').className = isMatchValid ? 'rule valid' : 'rule';
    // Update the text of the match rule div to show a green checkmark or red X respectively
    document.getElementById('rule-match').innerText = isMatchValid ? '✅ PINs must match' : '❌ PINs must match';

    // Retrieve and trim whitespace from the first name input field
    const first = document.getElementById('firstName').value.trim();
    // Retrieve and trim whitespace from the last name input field
    const last = document.getElementById('lastName').value.trim();
    // Retrieve and trim whitespace from the email input field
    const email = document.getElementById('email').value.trim();
    // Retrieve and trim whitespace from the app password input field
    const appPass = document.getElementById('appPassword').value.trim();
    // Retrieve the main sign up submit button element
    const btn = document.getElementById('signupBtn');

    // Check if all three PIN rules are valid AND none of the text fields are blank
    if (isLengthValid && isNumValid && isMatchValid && first !== "" && last !== "" && email !== "" && appPass !== "") {
        // If all conditions are met, remove the disabled attribute from the submit button
        btn.disabled = false; 
        // Restore the visual opacity of the submit button to 100%
        btn.style.opacity = '1';
    } else {
        // If any condition fails, re-apply the disabled attribute to the submit button
        btn.disabled = true; 
        // Drop the visual opacity of the submit button to 50% to show it is inactive
        btn.style.opacity = '0.5';
    }
};

// Define a globally accessible function to handle writing the new user to the database
window.createAccount = function() {
    // Construct a new user object mapping all the values from the DOM to properties
    const userObj = {
        // Map the trimmed first name value to the firstName property
        firstName: document.getElementById('firstName').value.trim(),
        // Map the trimmed last name value to the lastName property
        lastName: document.getElementById('lastName').value.trim(),
        // Map the trimmed email value, converted to lowercase for consistency, to the email property
        email: document.getElementById('email').value.trim().toLowerCase(),
        // Map the trimmed app password value to the appPassword property
        appPassword: document.getElementById('appPassword').value.trim(),
        // Map the raw 4-digit PIN value to the pin property
        pin: document.getElementById('pin').value
    };

    // Fetch the existing user database from local storage, or initialize an empty object
    const users = JSON.parse(localStorage.getItem('mathTrackUsers')) || {};
    
    // Check if a user with the same email already exists in the local database
    if (users[userObj.email]) {
        // Alert the user and immediately exit the function if the email is taken
        return alert("An account with this email already exists!");
    }

    // Assign the new user object to the users database using the email as the unique key
    users[userObj.email] = userObj;
    // Stringify and save the updated users database back into local storage
    localStorage.setItem('mathTrackUsers', JSON.stringify(users));
    
    // Set the newly created user as the active current session in local storage
    localStorage.setItem('currentUser', JSON.stringify(userObj));
    // Redirect the browser window to the class selection page
    window.location.href = 'select.html';
};

// Define an asynchronous function to handle sending the recovery code email
window.sendCode = async function() {
    // Fetch, trim, and lowercase the email provided by the user in step 1
    const emailInput = document.getElementById('email').value.trim().toLowerCase();
    // Fetch the user database from local storage to verify the account exists
    const users = JSON.parse(localStorage.getItem('mathTrackUsers')) || {};

    // Check if the email field was left completely blank
    if (!emailInput) {
        // Alert the user and stop execution if blank
        return alert("Please enter your email.");
    }
    // Check if the provided email actually exists in the local database
    if (!users[emailInput]) {
        // Alert the user and stop execution if the email is not registered
        return alert("No account found matching that email.");
    }

    // Set the global targetEmail variable to the validated email input
    targetEmail = emailInput;
    // Generate a random 4-digit code by calculating a math floor between 1000 and 9999, then convert to string
    generatedCode = Math.floor(1000 + Math.random() * 9000).toString();

    // Get the "Send Recovery Code" button element from the DOM
    const btn = document.getElementById('sendBtn');
    // Change the button text to inform the user that the sending process is ongoing
    btn.innerText = "Sending...";
    // Disable the button to prevent the user from clicking it multiple times
    btn.disabled = true;

    // Open a try-catch block to handle the asynchronous network request safely
    try {
        // Await a POST request to the local Node.js server API endpoint for recovery
        const response = await fetch('http://localhost:3000/api/send-recovery', {
            // Specify the HTTP method as POST
            method: 'POST',
            // Define the request headers to declare the payload as JSON data
            headers: { 'Content-Type': 'application/json' },
            // Stringify the payload containing the target email and the generated code
            body: JSON.stringify({ email: targetEmail, code: generatedCode })
        });

        // Check if the server responded with an OK (200) status
        if (response.ok) {
            // Hide the UI block representing step 1 (entering the email)
            document.getElementById('step1').style.display = 'none';
            // Reveal the UI block representing step 2 (entering the code and new PIN)
            document.getElementById('step2').style.display = 'block';
            // Update the instructional text at the top to confirm the email was dispatched
            document.getElementById('instructionText').innerText = `Recovery code sent to ${targetEmail}`;
        } else {
            // Alert the user if the server responded with an error code
            alert("Failed to send email. Check server console.");
            // Reset the button text back to its original state
            btn.innerText = "Send Recovery Code";
            // Re-enable the button so the user can try again
            btn.disabled = false;
        }
    } catch (err) {
        // Alert the user if the fetch request failed entirely (e.g., server is offline)
        alert("Server offline. Ensure your node server is running.");
        // Reset the button text back to its original state
        btn.innerText = "Send Recovery Code";
        // Re-enable the button so the user can try again
        btn.disabled = false;
    }
};

// Define a globally accessible function to validate the recovery form dynamically
window.validateRecoveryForm = function() {
    // Retrieve the string value from the new PIN input field
    const pin = document.getElementById('newPin').value;
    // Retrieve the string value from the confirm PIN input field
    const conf = document.getElementById('confPin').value;
    // Retrieve and trim the string value from the recovery code input field
    const code = document.getElementById('recoveryCode').value.trim();

    // Create a boolean flag evaluating if the new PIN is exactly 4 characters long
    let isLengthValid = pin.length === 4;
    // Create a boolean flag evaluating if the new PIN consists solely of digits using RegEx
    let isNumValid = /^\d+$/.test(pin);
    // Create a boolean flag evaluating if the new PIN matches the confirm PIN and is not blank
    let isMatchValid = (pin === conf) && pin.length > 0;

    // Update the CSS class of the length rule div based on the flag status
    document.getElementById('rule-length').className = isLengthValid ? 'rule valid' : 'rule';
    // Update the inner text of the length rule div to show the corresponding visual checkmark or X
    document.getElementById('rule-length').innerText = isLengthValid ? '✅ Must be exactly 4 characters' : '❌ Must be exactly 4 characters';
    
    // Update the CSS class of the numeric rule div based on the flag status
    document.getElementById('rule-number').className = isNumValid && pin.length > 0 ? 'rule valid' : 'rule';
    // Update the inner text of the numeric rule div to show the corresponding visual checkmark or X
    document.getElementById('rule-number').innerText = isNumValid && pin.length > 0 ? '✅ Must contain only numbers' : '❌ Must contain only numbers';
    
    // Update the CSS class of the match rule div based on the flag status
    document.getElementById('rule-match').className = isMatchValid ? 'rule valid' : 'rule';
    // Update the inner text of the match rule div to show the corresponding visual checkmark or X
    document.getElementById('rule-match').innerText = isMatchValid ? '✅ PINs must match' : '❌ PINs must match';

    // Retrieve the reset password final submission button element
    const resetBtn = document.getElementById('resetBtn');

    // Verify all three PIN validation rules are true and that the inputted recovery code is exactly 4 characters
    if (isLengthValid && isNumValid && isMatchValid && code.length === 4) {
        // If all logic checks out, remove the disabled attribute from the reset button
        resetBtn.disabled = false; 
        // Restore full 100% opacity to the reset button to visually show it is clickable
        resetBtn.style.opacity = '1';
    } else {
        // If any check fails, re-apply the disabled attribute to the reset button
        resetBtn.disabled = true; 
        // Drop the opacity to 50% to visually indicate the button is inactive
        resetBtn.style.opacity = '0.5';
    }
};

// Define a globally accessible function to finalize the password reset
window.resetPassword = function() {
    // Retrieve and trim the value from the recovery code input field
    const codeInput = document.getElementById('recoveryCode').value.trim();
    // Cross-reference the inputted code with the generated code stored in the global variable
    if (codeInput !== generatedCode) {
        // Alert the user if the codes do not match identically
        alert("Incorrect recovery code. Please check your email.");
        // Break out of the function to stop the reset process
        return;
    }

    // Retrieve the full user database from local storage
    const users = JSON.parse(localStorage.getItem('mathTrackUsers')) || {};
    
    // Target the specific user in the database and overwrite their pin property with the newly validated PIN
    users[targetEmail].pin = document.getElementById('newPin').value;
    // Serialize and save the updated users database back to local storage
    localStorage.setItem('mathTrackUsers', JSON.stringify(users));

    // Fetch the active session token from local storage to check if someone was already logged in
    const currentUser = JSON.parse(localStorage.getItem('currentUser'));
    // Verify that an active session exists AND that it belongs to the user who just reset their password
    if (currentUser && currentUser.email === targetEmail) {
        // Update the active session token's PIN property to match the new one to prevent desync
        currentUser.pin = document.getElementById('newPin').value;
        // Resave the updated active session token back to local storage
        localStorage.setItem('currentUser', JSON.stringify(currentUser));
    }

    // Fire an alert to let the user know the backend processing was successful
    alert("PIN successfully reset! You can now log in.");
    // Redirect the user back to the primary index/login page
    window.location.href = 'index.html';
};